# Generated by Django 5.1.3 on 2026-01-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sync_role_with_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('recruiter', 'Recruiter'), ('hr_admin', 'HR Admin'), ('system_admin', 'System Admin'), ('hr_recruiter', 'HR Recruiter'), ('hr_manager', 'HR Manager'), ('it_support', 'IT Support'), ('admin', 'Admin'), ('superadmin', 'Super Admin'), ('applicant', 'Applicant')], default='applicant', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('recruiter', 'Recruiter'), ('hr_admin', 'HR Admin'), ('system_admin', 'System Admin'), ('hr_recruiter', 'HR Recruiter'), ('hr_manager', 'HR Manager'), ('it_support', 'IT Support'), ('admin', 'Admin'), ('superadmin', 'Super Admin'), ('applicant', 'Applicant')], default='recruiter', max_length=20),
        ),
    ]
