# Generated by Django 5.1.3 on 2026-01-20 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('application_source', models.CharField(choices=[('walk_in', 'Walk-in'), ('online', 'Online Website')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('passed', 'Passed - Interview'), ('failed', 'Failed - Interview'), ('hired', 'Hired'), ('failed_training', 'Failed - Training'), ('failed_onboarding', 'Failed - Onboarding'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('reapplication_date', models.DateField(blank=True, help_text='Date when applicant can reapply', null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text="Applicant's latitude during application", max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text="Applicant's longitude during application", max_digits=10, null=True)),
                ('distance_from_office', models.DecimalField(blank=True, decimal_places=2, help_text='Distance in meters from office', max_digits=10, null=True)),
                ('geo_status', models.CharField(choices=[('onsite', 'Onsite'), ('offsite', 'Offsite'), ('unknown', 'Unknown')], default='unknown', help_text='Classification of applicant location relative to office geofence', max_length=10)),
                ('interview_completed', models.BooleanField(default=False, help_text='True when applicant finished interview')),
                ('phase2_token_issued_at', models.DateTimeField(blank=True, help_text='Timestamp of latest phase2 token', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Applicant',
                'verbose_name_plural': 'Applicants',
                'db_table': 'applicants',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, help_text='Office latitude in decimal degrees', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Office longitude in decimal degrees', null=True)),
                ('radius_km', models.FloatField(default=10, help_text='Geofence radius in kilometers')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Office Location',
                'verbose_name_plural': 'Office Locations',
                'db_table': 'office_locations',
            },
        ),
        migrations.CreateModel(
            name='ApplicantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('resume', 'Resume'), ('cover_letter', 'Cover Letter'), ('id_document', 'ID Document'), ('certificate', 'Certificate'), ('other', 'Other')], max_length=20)),
                ('file_path', models.FileField(upload_to='applicant_documents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applicants.applicant')),
            ],
            options={
                'verbose_name': 'Applicant Document',
                'verbose_name_plural': 'Applicant Documents',
                'db_table': 'applicant_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='applicant',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants', to='applicants.officelocation'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['status'], name='idx_applicant_status'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['application_date'], name='idx_applicant_appdate'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['email'], name='idx_applicant_email'),
        ),
    ]
