# Generated by Django 5.1.3 on 2025-12-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0004_alter_applicant_latitude_alter_applicant_longitude'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['status'], name='idx_applicant_status'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['application_date'], name='idx_applicant_appdate'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['email'], name='idx_applicant_email'),
        ),
    ]
