# Generated by Codex for Phase 2 training cleanup.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS training_trainingresponse;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS training_trainingsession;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS training_trainingmodule;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
