# Generated by Django 5.1.3 on 2025-12-09 02:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0005_applicant_idx_applicant_status_and_more'),
        ('interviews', '0008_interview_error_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['status'], name='idx_interview_status'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['created_at'], name='idx_interview_created'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['applicant'], name='idx_interview_applicant'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['position_type'], name='idx_interview_position'),
        ),
        migrations.AddIndex(
            model_name='videoresponse',
            index=models.Index(fields=['uploaded_at'], name='idx_vr_uploaded_at'),
        ),
        migrations.AddIndex(
            model_name='videoresponse',
            index=models.Index(fields=['status'], name='idx_vr_status'),
        ),
        migrations.AddIndex(
            model_name='videoresponse',
            index=models.Index(fields=['interview'], name='idx_vr_interview'),
        ),
    ]
