# Generated by Django 5.2.8 on 2025-12-10 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0006_officelocation_applicant_office'),
        ('interviews', '0009_interview_idx_interview_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='positiontype',
            name='offices',
            field=models.ManyToManyField(blank=True, help_text='Offices where this position is available', related_name='position_types', to='applicants.officelocation'),
        ),
    ]
