# Generated by Django 5.2.8 on 2025-12-10 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0006_officelocation_applicant_office'),
        ('interviews', '0010_positiontype_offices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positiontype',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Job Category', 'verbose_name_plural': 'Job Categories'},
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_positions', to='interviews.positiontype')),
                ('offices', models.ManyToManyField(blank=True, related_name='job_positions', to='applicants.officelocation')),
            ],
            options={
                'verbose_name': 'Job Position',
                'verbose_name_plural': 'Job Positions',
                'db_table': 'job_positions',
                'ordering': ['-created_at'],
            },
        ),
    ]
