# Generated by Django 5.1.3 on 2025-12-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0021_positiontype_description_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewquestion',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='(Deprecated) legacy subrole tags; use competency instead.'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='subroles',
            field=models.JSONField(blank=True, default=list, help_text='(Deprecated) legacy subroles; questions are competency-based.'),
        ),
    ]
